In [ ]:
import numpy as np
np.random.seed(42)
n=30
sensor_data = np.random.normal(loc=25, scale=2, size=n)
sensor_data = np.round(sensor_data)
print(sensor_data)

[26. 25. 26. 28. 25. 25. 28. 27. 24. 26. 24. 24. 25. 21. 22. 24. 23. 26.
 23. 22. 28. 25. 25. 22. 24. 25. 23. 26. 24. 24.]


In [ ]:
sensor_data[6]=11
sensor_data[17]=78
sensor_data[22]=56
print("Sensor_Data:\n",sensor_data)

Sensor_Data:
 [26. 25. 26. 28. 25. 25. 11. 27. 24. 26. 24. 24. 25. 21. 22. 24. 23. 78.
 23. 22. 28. 25. 56. 22. 24. 25. 23. 26. 24. 24.]


In [ ]:
mean = np.mean(sensor_data)
print("Mean:\n",mean)

Mean:
 26.866666666666667


In [ ]:
std = np.std(sensor_data)
print("Standard_Deviation:\n",std)

Standard_Deviation:
 11.473834968696773


In [52]:
window_size = 6
rolling_stat = np.lib.stride_tricks.sliding_window_view(sensor_data, window_size)
print("Rolling_Stat:\n",rolling_stack)

Rolling_Stat:
 [[26. 25. 26. 28. 25. 25.]
 [25. 26. 28. 25. 25. 11.]
 [26. 28. 25. 25. 11. 27.]
 [28. 25. 25. 11. 27. 24.]
 [25. 25. 11. 27. 24. 26.]
 [25. 11. 27. 24. 26. 24.]
 [11. 27. 24. 26. 24. 24.]
 [27. 24. 26. 24. 24. 25.]
 [24. 26. 24. 24. 25. 21.]
 [26. 24. 24. 25. 21. 22.]
 [24. 24. 25. 21. 22. 24.]
 [24. 25. 21. 22. 24. 23.]
 [25. 21. 22. 24. 23. 78.]
 [21. 22. 24. 23. 78. 23.]
 [22. 24. 23. 78. 23. 22.]
 [24. 23. 78. 23. 22. 28.]
 [23. 78. 23. 22. 28. 25.]
 [78. 23. 22. 28. 25. 56.]
 [23. 22. 28. 25. 56. 22.]
 [22. 28. 25. 56. 22. 24.]
 [28. 25. 56. 22. 24. 25.]
 [25. 56. 22. 24. 25. 23.]
 [56. 22. 24. 25. 23. 26.]
 [22. 24. 25. 23. 26. 24.]
 [24. 25. 23. 26. 24. 24.]]


In [ ]:
r_mean = np.mean(rolling_stat, axis= 1)
#r_mean = np.round(mean)
print("Rolling_Stat Mean:\n",r_mean)

Rolling_Stack Mean:
 [25.83333333 23.33333333 23.66666667 23.33333333 23.         22.83333333
 22.66666667 25.         24.         23.66666667 23.33333333 23.16666667
 32.16666667 31.83333333 32.         33.         33.16666667 38.66666667
 29.33333333 29.5        30.         29.16666667 29.33333333 24.
 24.33333333]


In [ ]:
r_std = np.std(rolling_stat, axis=1)
print("Rolling_Stat Std:\n",r_std)

Rolling_Stack Std:
 [ 1.06718737  5.61743318  5.76387216  5.67646212  5.44671155  5.39804491
  5.34373985  1.15470054  1.52752523  1.69967317  1.37436854  1.34370962
 20.53790534 20.6673387  20.58316464 20.2155056  20.14461604 21.10028962
 12.1060132  12.02428099 11.76151918 12.04736025 11.99536948  1.29099445
  0.94280904]


In [ ]:
z_score = (sensor_data - mean)/std
print("Z_Score:\n",z_score)

Z_Score:
 [-0.07553418 -0.16268899 -0.07553418  0.09877546 -0.16268899 -0.16268899
 -1.38285645  0.01162064 -0.24984381 -0.07553418 -0.24984381 -0.24984381
 -0.16268899 -0.51130827 -0.42415345 -0.24984381 -0.33699863  4.45651637
 -0.33699863 -0.42415345  0.09877546 -0.16268899  2.53911037 -0.42415345
 -0.24984381 -0.16268899 -0.33699863 -0.07553418 -0.24984381 -0.24984381]


In [ ]:
outlier_mask = np.abs(z_score) > 2
print("Outlier Mask:\n", outlier_mask)

Outlier Mask:
 [False False False False False False False False False False False False
 False False False False False  True False False False False  True False
 False False False False False False]


In [ ]:
outliers = sensor_data[outlier_mask]
print("Outliers:\n", outliers)

Outliers:
 [78. 56.]
